version: "3"
services:
  dozzle:
    container_name: nginx
    image: nginx:1.25.4-bookworm
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/common:/etc/nginx/common
      - ./conf/authelia:/etc/nginx/authelia
      - /var/log/nginx:/var/log/nginx
    network_mode: bridge
    ports:
      - 8080:80